language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm
script:
  # - npm run examples:lint
  # - npm run examples:test
branches:
  only:
    # - master
cache:
  directories:
  # - examples/real-world/node_modules
  # - examples/shopping-cart/node_modules